sudo: false
language: node_js
node_js:
  - 5.6.0
matrix:
  fast_finish: true
before_install:
  - gem update --system
  - gem install sass
  - npm install -g gulp
cache:
  directories:
    - node_modules
